# Generated by Django 5.2.12 on 2026-04-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='category',
            new_name='tasks_categ_user_id_57adb5_idx',
            old_name='tasks_categ_user_id_0b4f8c_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_user_id_c0fce1_idx',
            old_name='tasks_task_user_id_8ffd9e_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_user_id_075050_idx',
            old_name='tasks_task_user_id_d4424d_idx',
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_task_user_id_66b666_idx',
            old_name='tasks_task_user_id_4fbca6_idx',
        ),
    ]
